### ISSUE TITLE
No matching variant of io.insert-koin:koin-ktor:3.2.0 was found

### ISSUE THREAD

**Issue by Ahmard** [InsertKoinIO/koin-ktor#2]
**Describe the bug**
remote:        FAILURE: Build failed with an exception.
remote:        
remote:        * What went wrong:
remote:        Execution failed for task ':compileKotlin'.
remote:        > Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
remote:           > Could not resolve all files for configuration ':compileClasspath'.
remote:              > Could not resolve io.insert-koin:koin-ktor:3.2.0.
remote:                Required by:
remote:                    project :
remote:                 > No matching variant of io.insert-koin:koin-ktor:3.2.0 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
remote:                     - Variant 'apiElements' capability io.insert-koin:koin-ktor:3.2.0 declares an API of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
remote:                         - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
remote:                     - Variant 'runtimeElements' capability io.insert-koin:koin-ktor:3.2.0 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
remote:                         - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
remote:        
remote:        * Try:
remote:        > Run with --stacktrace option to get the stack trace.
remote:        > Run with --info or --debug option to get more log output.
remote:        > Run with --scan to get full insights.

**To Reproduce**
1. Install koin using: implementation("io.insert-koin:koin-ktor:3.2.0")
2. Try to deploy to Heroku App

**Expected behavior**
To works fine as it's working in local environment

**Koin project used and used version (please complete the following information):**
 [e.g]: `koin-core version 0.9.2`
io.insert-koin:koin-ktor:3.2.0.

**Additional moduleDefinition**
Add any other moduleDefinition about the problem here.

**Comment by Ahmard** [comment]
Almost forgotten, it's working fine in my computer.

**Comment by hnljp** [comment]
It is requiring Java 11, but your build server is using java 8 at this moment.

**Comment by Ahmard** [comment]
Yes, installing Java 11 fixed it.
Thank you.
